#!/bin/sh
#
# qw-serverd	qw-serverd QuakeWorld Server
#
# chkconfig:	4 100 100
#
# description:	qw-serverd QuakeWorld Server

# Functions library
. /etc/rc.d/init.d/functions

case "$1" in
  start)
	# Check if the service is already running?
	if [ ! -f /var/lock/subsys/qw-serverd ]; then
		msg_starting "QuakeWorld Server"
		busy
    		/usr/bin/qw-server > /dev/null &
		deltext
		ok
	else
		msg_already_running "QuakeWorld Server"
	        exit 1
	fi
	touch /var/lock/subsys/qw-serverd
	;;
  stop)

	if [ -f /var/lock/subsys/qw-serverd ]; then
		msg_stopping "QuakeWorld Server"
                killproc qw-server
                rm -f /var/lock/subsys/qw-serverd
        else
                msg_not_running "QuakeWorld Server"
                exit 1
	fi
	;;
  restart|reload)
        $0 stop
        $0 start
        ;;
  status)
	status /usr/bin/qw-server
	exit $?
	;;
  *)
	msg_usage "$0 {start|stop|restart|reload|status}"
	exit 1
esac

exit 0
