#!/bin/sh
# qw-serverd
#
# chkconfig:4 98 10
# description: QuakeWorld Server
# Functions library

. /etc/rc.d/init.d/functions

case "$1" in
  start)
	# Check if the service is already running?
	if [ ! -f /var/lock/subsys/qw-serverd ]; then
		msg_starting "QuakeWorld Server"
		busy
    		/usr/bin/qw-server > /dev/null &
		deltext
		ok
	else
		msg_Already_Running "QuakeWorld Server"
	        exit 1
	fi
	touch /var/lock/subsys/qw-serverd
	;;
  stop)

	if [ -f /var/lock/subsys/qw-serverd ]; then
		msg_stopping "QuakeWorld Server"
                killproc qw-server
                rm -f /var/lock/subsys/qw-serverd
        else
                msg_Not_Running "QuakeWorld Server"
                exit 1
	fi
	;;
  restart|reload)
        $0 stop
        $0 start
        ;;
  status)
	status /usr/bin/qw-server
	exit $?
	;;
  *)
	msg_Usage "$0 {start|stop|restart|reload|status}"
	exit 1
esac

exit 0
